<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\cart-icon.png" />
    <None Remove="Assets\made-in-jade.bmp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ErewhonExposures\ErewhonExposures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JadeSoftware.Joob-Ansi" Version="25.0.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\cart-icon.png" />
    <Resource Include="Assets\made-in-jade.bmp" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DELETE\TestShop.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="DELETE\TestShop.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
